[http]
host = "0.0.0.0"
httpPort = 8080 # http server port (recommended 80)
enableHttps = true # if true start https server and http will be redirect to https
httpsPort = 8443 # https server port (recommended 443)
cors = [ "localhost:8000" ] # CORS domains
tlsCert = "./cert.pem" # TLS certificate file
tlsKey = "./cert.key" # TLS key file

[jwt]
secret = "secret key used to sign tokens" # jsonwebtoken secret string used to sign tokens
expires = 24 # token expiration time in hours (default one day)

[storage]
path = "storage" # path to directory where user files will be stored
