# HTTP Server
[http]
# HTTP host
host = "0.0.0.0"
# HTTP port
port = 8080 
# Cors domains
cors = [
    "127.0.0.1:8000",
    "localhost:8000",
]

# Json Web Token
[jwt]
# JWT Secret string (used to sign tokens)
secret = "secret key used to sign tokens"
# Token expiration time in hours
expires = 24

# Storage
[storage]
# Directory where user files will be stored
path = "/home/homedisk"
