# HTTP Server
[http]
host = "0.0.0.0"
port = 8080
cors = [
    "127.0.0.1:8000",
    "localhost:8000",
]

# Json Web Token
[jwt]
secret = "secret key used to sign tokens" # secret used to sign tokens
expires = 24 # validity of token in hours

# Storage
[storage]
path = "/home/homedisk" # the folder where the user files will be stored
