[package]
name = "homedisk-types"
version = "0.0.0"
edition = "2021"

[features]
config = ["toml", "dirs"]

[dependencies]
thiserror = "1.0.30"
uuid = "1.0.0"
anyhow = "1.0.57"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.zeroize]
version = "1.5.4"
features = ["derive"]

[dependencies.axum]
version = "0.5.3"
optional = true

# config
[dependencies.toml]
version = "0.5.9"
optional = true
[dependencies.dirs]
version = "4.0.0"
optional = true
