[package]
name = "homedisk-types"
version = "0.0.0"
edition = "2021"

[features]
token = ["chrono", "jsonwebtoken"]
config = ["toml", "dirs"]

[dependencies]
thiserror = "1.0.30"
uuid = "0.8.2"
anyhow = "1.0.56"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.zeroize]
version = "1.5.4"
features = ["derive"]

[dependencies.axum]
version = "0.5.3"
optional = true

# config
[dependencies.toml]
version = "0.5.9"
optional = true
[dependencies.dirs]
version = "4.0.0"
optional = true

# token
[dependencies.chrono]
version = "0.4.19"
optional = true
[dependencies.jsonwebtoken]
version = "8.1.0"
optional = true
