[package]
name = "homedisk-types"
version = "0.0.0"
edition = "2021"

[features]
token = ["chrono", "jsonwebtoken"]

[dependencies]
thiserror = "1.0.30"
uuid = "0.8.2"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.axum]
version = "0.5.1"
optional = true

# token
[dependencies.chrono]
version = "0.4.19"
optional = true
[dependencies.jsonwebtoken]
version = "8.1.0"
optional = true
