[package]
name = "homedisk-types"
version = "0.0.0"
edition = "2021"

[features]
config = ["toml", "dirs"]
database = ["rust_utilities", "sqlx"]

[dependencies]
thiserror = "1.0.31"
uuid = "1.0.0"
anyhow = "1.0.57"
serde = { version = "1.0.137", features = ["derive"] }
zeroize = { version = "1.5.5", features = ["derive"] }
axum = { version = "0.5.4", optional = true }

# config
toml = { version = "0.5.9", optional = true }
dirs = { version = "4.0.0", optional = true }

# database
rust_utilities = { version = "0.2.0", optional = true }
sqlx = { version = "0.5.13", features = ["sqlite"], optional = true }
