[package]
name = "homedisk-utils"
version = "0.0.0"
edition = "2021"

[features]
default = ["crypto", "config", "database"]
crypto = ["sha-1", "sha2", "hex"]
config = ["toml", "anyhow"]
database = ["async-trait", "sqlx"]

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

# crypto
[dependencies.sha-1]
version = "0.10.0"
optional = true
[dependencies.sha2]
version = "0.10.2"
optional = true
[dependencies.hex]
version = "0.4.3"
optional = true

# config
[dependencies.toml]
version = "0.5.9"
optional = true
[dependencies.anyhow]
version = "1.0.56"
optional = true

# database
[dependencies.async-trait]
version = "0.1.53"
optional = true
[dependencies.sqlx]
version = "0.5.13"
features = ["runtime-tokio-rustls", "sqlite"]
optional = true
